version: '3.8'

services:
  pure-fa-om-exporter:
    image: quay.io/purestorage/pure-fa-om-exporter:latest
    command: 
      - '--port=9490'
    depends_on: 
      - prometheus
    ports:
      - 9490:9490
    restart: on-failure
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--storage.tsdb.retention=60d'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: on-failure
volumes:
  prometheus-data:
  grafana-data: