global:
  scrape_interval:     60s
  scrape_timeout:      50s
scrape_configs:
  - job_name: 'purestorage-fa'
    metrics_path: /metrics/array
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray1
        env: 'Prod'

  - job_name: 'purestorage-fa_volumes'
    metrics_path: /metrics/volumes
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray1
        env: 'Prod'

  - job_name: 'purestorage-fa_hosts'
    metrics_path: /metrics/hosts
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray1
        env: 'Prod'
        
  - job_name: 'purestorage-fa_pods'
    metrics_path: /metrics/pods
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray1
        env: 'Prod'
 
  - job_name: 'purestorage-fa_directories'
    metrics_path: /metrics/directories
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray1
        env: 'Prod'
 

  - job_name: 'purestorage-fa2'
    metrics_path: /metrics/array
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray2
        env: 'Prod'

  - job_name: 'purestorage-fa2_volumes'
    metrics_path: /metrics/volumes
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray2
        env: 'Prod'

  - job_name: 'purestorage-fa2_hosts'
    metrics_path: /metrics/hosts
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray2
        env: 'Prod'
        
  - job_name: 'purestorage-fa2_pods'
    metrics_path: /metrics/pods
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray2
        env: 'Prod'
 
  - job_name: 'purestorage-fa2_directories'
    metrics_path: /metrics/directories
    authorization:
      credentials: 2f316e6a-b326-1bcd-3b7a-bc4e7f1499c7
    params:
      endpoint: [192.168.0.16]

    static_configs:
    - targets:
      - pure-fa-om-exporter:9490
      labels:
        location: US
        site: Prod
        instance: FlashArray2
        env: 'Prod'